spring:
  application:
      name: auth-server
#  jpa:
#    open-in-view: true
#    database: POSTGRESQL
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#  datasource:
#    platform: postgres
#    url: jdbc:postgresql://192.168.1.140:5432/auth
#    username: wang
#    password: yunfei
#    driver-class-name: org.postgresql.Driver
  redis:
    host: 127.0.0.1

server:
  port: 9999


eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.host:localhost}:${eureka.port:8761}/eureka/



logging.level.org.springframework.security: DEBUG

logging.leve.org.springframework: DEBUG


security:
  oauth2:
    resource:
      filter-order: 3